defaults:
  - optimizer: adam
  - scheduler: reduce_on_plateau

_target_: schnetpack_gschnet.ConditionalGenerativeSchNetTask
scheduler_args:
  mode: min
  factor: 0.5
  patience: 10
  min_lr: 1e-6
  smoothing_factor: 0.0
