# @package _global_
defaults:
  - generate: default_generate
  - _self_

modeldir: ???
outputfile: null
workdir: null
remove_workdir: False

use_gpu: True
print_config: True
view_molecules: False

debug:
  run: False
  print_progress: False
  view_progress: False

settings:
  conditions:
    trajectory: ${generate.conditions}

# hydra configuration
hydra:
    job:
        chdir: True
    # output paths for hydra logs
    run:
        dir: ${modeldir}

    # disable hydra config storage, since handled manually
    output_subdir: null

    help:
      app_name: schnetpack-gschnet G-SchNet Generate

      template: |-
        SchNetPack

        == Configuration groups ==
        Compose your configuration from those groups (db=mysql)

        $APP_CONFIG_GROUPS

        == Config ==
        This is the config generated for this run.
        You can change the config file to be loaded to a predefined one
        > generate.py --config-name=generate_molecules

        or your own:
        > generate.py --config-dir=./my_configs --config-name=my_config

        You can override everything, for example:
        > generate.py --config-name=generate_molecules outputfile=/path/to/out.db generate.batch_size=50 --help

        -------
        $CONFIG
        -------

        ${hydra.help.footer}